class EdgeALP:
    def __init__(self, origin, destination, cost, pheromony=None):
        """
        :param origin: Start point
        :param destination: End point
        :param cost: Cost associate to the edge generated by (origin, destination)
        :param pheromony: Represents the total amount of pheromny for this edge
        """

        self.origin = origin
        self.destination = destination
        self.cost = cost
        self.pheromony = pheromony

    def get_origin(self):
        return self.origin

    def get_destination(self):
        return self.destination

    def get_cost(self):
        return self.cost

    def get_pheromony(self):
        return self.pheromony

    def set_pheromony(self, pheromony):
        self.pheromony = pheromony
